source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Data Falsa
# Faker is used to easily generate fake data: names, addresses, phone numbers, etc. https://github.com/faker-ruby/faker
gem 'faker' #, :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'

# Paginacion
# Kaminari is a paginator for Rails https://github.com/kaminari/kaminari
gem 'kaminari'

# Estilo para kaminari 
# Bootstrap 4 styling for Kaminari https://github.com/KamilDzierbicki/bootstrap4-kaminari-views
gem 'bootstrap4-kaminari-views'

# Ransack para formularios de busqueda
# Ransack is use to implement advanced search capability https://activerecord-hackery.github.io/ransack/
gem 'ransack'

# Use jQuery with Rails 4+ https://github.com/rails/jquery-rails
gem 'jquery-rails'

# CoffeeScript adapter for the Rails asset pipeline. https://github.com/rails/coffee-rails
  # we need to use rake rails tmp:cache:clear
# gem 'coffee-rails', '~> 4.1', '>= 4.1.1'

# Dependent Fields for Rails https://github.com/vollnhals/dependent-fields-rails makes it easy to hide or show dependent fields in forms based on select or checkbox values.
# Dependencies - Be sure to include CDN's (underscorejs and jquery) in your file /app/controllers/application.html.erb (Head section).
# gem 'dependent-fields-rails'

# underscore.js works with dependent-fileds https://github.com/rweng/underscore-rails asset pipeline provider/wrapper
# gem 'underscore-rails'

# jQuery plugin for drop-in fix binded events problem caused by Turbolinks https://github.com/kossnocorp/jquery.turbolinks
# gem 'jquery-turbolinks'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data" #, platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  
  # A mini view framework for console/irb that's easy to use, even while under its influence. http://tagaholic.me/hirb/
  gem "hirb"

end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
